# Generated by Django 3.2.9 on 2023-06-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_item_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
