# Generated by Django 3.2.9 on 2023-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, max_length=2000, null=True),
        ),
    ]
