# Generated by Django 3.2.9 on 2023-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
